### ISSUE TITLE
[PE-D][Tester A] Timetable is not reflected in the record

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103-T14-1/tp#175] opened 2024-04-05 17:28 UTC
add n/jake s/A1111112D e/jake@gmail.com h/@jakeTele c/mon: 8-10

When the above command is entered, the timetable is not inserted inside the record. Based on the below picture, the timetable for Monday is shown as "no periods". 

![image.png](https://raw.githubusercontent.com/AndrewOng2066/ped/main/files/17e964fc-d07a-4d32-bac0-b7a3b717351a.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: AndrewOng2066/ped#1

**Comment by marclamp** [comment] 2024-04-07 13:15
Duplicate of #137

**Closed by marclamp** 2024-04-07 13:15 UTC
Labels: duplicate
